version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/Oslo
  open-pull-requests-limit: 15
  ignore:
  - dependency-name: org.projectlombok:lombok
    versions:
    - ">= 1.18.a"
    - "< 1.19"
